# Generated by Django 5.0.6 on 2024-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='current_year',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='growth_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='last_year',
            field=models.FloatField(null=True),
        ),
    ]
